apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: remote123/whiteboxlearning:wbl-backend125
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "production"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SECRET_KEY
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_FROM
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_PORT
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_SERVER
            - name: MAIL_STARTTLS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_STARTTLS
            - name: MAIL_SSL_TLS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_SSL_TLS
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EMAIL_PASS
            - name: TO_RECRUITING_EMAIL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TO_RECRUITING_EMAIL
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SMTP_SERVER
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SMTP_PORT
            - name: RESET_PASSWORD_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: RESET_PASSWORD_URL
          resources:
            requests:
              cpu: "200m"      # Minimum CPU requested
              memory: "256Mi"  # Minimum memory requested
            limits:
              cpu: "500m"      # Max CPU usage
              memory: "512Mi"  # Max memory usage
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer # For internal access, with Ingress managing external access
