apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbl-resume-backend-deployment
  labels:
    app: wbl-resume-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wbl-resume-backend
  template:
    metadata:
      labels:
        app: wbl-resume-backend
    spec:
      containers:
        - name: wbl-resume-backend
          image: remote123/whiteboxlearning:resume-view-wbl
          ports:
            - containerPort: 8001
          env:
            - name: ENV
              value: "production"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SECRET_KEY
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: CLIENT_SECRET
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: REDIRECT_URI
          resources:
            requests:
              cpu: "200m"      # Minimum CPU requested
              memory: "256Mi"  # Minimum memory requested
            limits:
              cpu: "500m"      # Max CPU usage
              memory: "512Mi"  # Max memory usage
---
apiVersion: v1
kind: Service
metadata:
  name: wbl-resume-backend-service
spec:
  selector:
    app: wbl-resume-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
